version: 2.1

jobs:
  print-hello:
    environment:
      BASH_ENV: hihi
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo $BASH_ENV
  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world

workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
