version: 2.1

commands:
  sayhello:
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo "Hello << parameters.to >>"
      - run:
          name: Run commands
          command: |
              echo "I will exit"
              exit 1
      - run:
          name: run on fail
          command: |
              echo "run fail"
          when: on_fail

jobs:
  say-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - sayhello:
          to: "hihihi"

  # print-hello:
  #   environment:
  #     BASH_ENV: hihi
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - run: echo $BASH_ENV
  # print-world:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - run: echo world
  # save_hello_world_output:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - run: echo "hello" > ~/output.txt
  #     - persist_to_workspace:
  #         root: ~/
  #         paths:
  #           - output.txt
  # print-output-file:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - run: cat ~/output.txt

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      # - save_hello_world_output
      # - print-output-file:
      #     requires:
      #       - save_hello_world_output
      # - print-hello
      # - print-world:
      #     requires:
      #       - print-hello
